### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by klxq** [trotyl/tw-secondhand#20]
## This is a common component

- [ ] Bug/Defect
- [x] Feature/Story
- [ ] Enhancement

## Current behavior

- None

## Expected behavior

- Two status, one is normal, the other is disabled
- Customize click event
- Unbind click event when status of button is disabled
- Support redirect functionality 

## Acceptance Criteria

<pre><code>
Checklist:
- [ ] item 1
- [ ] item 2
</code></pre>

Others:

**Comment by futantan** [comment]
@klxq 这个 Component @trotyl 已经做了。
